### ISSUE TITLE
Server crash on Windows

### ISSUE THREAD

**Issue by nhandl3** [bradfitz/rfbgo#1]
Hi bradfitz,
Nice project, but it crash `panic: only true-colour supported` when I run on Windows and connect to your server via RealVNC viewer,

```
d:\toollib\go-libs\src\github.com\bradfitz\rfbgo>go run demo.go
2015/04/08 08:21:01 client wants: "RFB 003.008\n"
2015/04/08 08:21:01 reading client init
2015/04/08 08:21:01 Client encodings: []int32{16, 1, 22, 21, 15, 6, 5, 2, 0, -31
1, -239, -223}
2015/04/08 08:21:01 handling setpixel format
2015/04/08 08:21:01 Client wants pixel format: rfb.PixelFormat{BPP:0x8, Depth:0x
8, BigEndian:0x0, TrueColour:0x0, RedMax:0x0, GreenMax:0x0, BlueMax:0x0, RedShif
t:0x0, GreenShift:0x0, BlueShift:0x0}
panic: only true-colour supported

goroutine 24 [running]:
runtime.panic(0x514100, 0xc082000690)
        c:/go/src/pkg/runtime/panic.c:279 +0x11f
github.com/bradfitz/rfbgo/rfb.(*Conn).failf(0xc082044160, 0x5a0390, 0x1a, 0x0, 0
x0, 0x0)
        d:/toollib/go-libs/src/github.com/bradfitz/rfbgo/rfb/rfb.go:191 +0x99
github.com/bradfitz/rfbgo/rfb.(*Conn).pushImage(0xc082044160, 0xc082009e30)
        d:/toollib/go-libs/src/github.com/bradfitz/rfbgo/rfb/rfb.go:371 +0x256
github.com/bradfitz/rfbgo/rfb.(*Conn).pushFrame(0xc082044160, 0x500000000000000,
 0x7d02d0)
        d:/toollib/go-libs/src/github.com/bradfitz/rfbgo/rfb/rfb.go:350 +0x4c1
github.com/bradfitz/rfbgo/rfb.(*Conn).pushFramesLoop(0xc082044160)
        d:/toollib/go-libs/src/github.com/bradfitz/rfbgo/rfb/rfb.go:311 +0xc3
created by github.com/bradfitz/rfbgo/rfb.(*Conn).handleUpdateRequest
        d:/toollib/go-libs/src/github.com/bradfitz/rfbgo/rfb/rfb.go:528 +0xd2
```

What should I do to overcome this problem?
Thank you

**Comment by nhandl3** [comment]
I set RealVNC option `FullColor` to `true` then I connected successfully and could see waves of color.
